 http:
  routers:
    nextcloud-https:
      rule: Host(`nextcloud.domain.tld`)
      entryPoints:
        - https
      service: nextcloud
      middlewares:
        - nextcloud-dav-redirect
        - security-headers
      tls: {}
    
    nextcloud-redirect:
      rule: Host(`nextcloud.domain.tld`)
      entryPoints:
        - http
      service: nextcloud
      middlewares:
        - https-redirect
        
  middlewares:
    nextcloud-dav-redirect:
      redirectRegex:
        permanent: true
        regex: http://(.*)/.well-known/(card|cal)dav
        replacement: http://$$1/remote.php/dav/

  services:
    nextcloud:
      loadBalancer:
        servers:
        - url: http://nextcloud_web:80