version: '3.5'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    
  app:
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
      - redis

  web:
    container_name: nextcloud_web
    build: ./web
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    networks:
      - public
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud-router.loadbalancer.server.port=80"
      # Middlewares
      - "traefik.http.middlewares.nextcloud-dav-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-dav-redirect.redirectregex.regex=http://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav-redirect.redirectregex.replacement=http://$$1/remote.php/dav/"
      # Redirect
      - "traefik.http.routers.nextcloud-redirect.rule=Host(`nextcloud.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-redirect.entrypoints=http"
      - "traefik.http.routers.nextcloud-redirect.middlewares=https-redirect@file"
      - "traefik.http.routers.nextcloud-redirect.service=nextcloud-router"
      # Router
      - "traefik.http.routers.nextcloud-router.rule=Host(`nextcloud.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-router.entrypoints=https"
      - "traefik.http.routers.nextcloud-router.middlewares=security-headers@file, nextcloud-dav-redirect@docker"
      - "traefik.http.routers.nextcloud-router.service=nextcloud-router"
      - "traefik.http.routers.nextcloud-router.tls.certresolver=letsencrypt"

volumes:
  redis:
  db:
  nextcloud:

networks:
  public:
    external: true
    name: public
