version: '3.5'

networks:
  public:
    external: false
    name: public

services:
  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/data/traefik:/var/traefik
    networks:
      - public
    command:
      # Logs
      - "--log.level=INFO"
      - "--log.filePath=/var/traefik/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/traefik/logs/access.log"
      # Api
      - "--api.dashboard=true"
      # Providers
      - "--providers.file.filename=/etc/traefik/security.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=public"
      # Entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entryPoints.internal.address=:8443"
      # Certificate Resolvers
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/var/traefik/certs/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${LOCAL_DOMAIN:-lan}`)"
      - "traefik.http.routers.traefik.entrypoints=internal"
      - "traefik.http.routers.traefik.middlewares=auth@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    volumes:
      - /srv/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${LOCAL_DOMAIN:-lan}`)"
      - "traefik.http.routers.portainer.entrypoints=internal"
      - "traefik.http.routers.portainer.tls=true"