version: '3.5'

services:
  
  traefik:
    image: traefik:v2.1.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik:/var/traefik
    networks:
      - public
      - default

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik:
  portainer:

networks:
  public:
    external: false
    name: public