version: '3.5'

networks:
  default:
    external:
      name: public

services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    volumes:
      - /srv/data/jellyfin/config:/config
      - /srv/data/jellyfin/cache:/cache
      #- /path/to/media:/media
    # network_mode: "host"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin-service.loadbalancer.server.port=8096"
      # Router
      - "traefik.http.routers.jellyfin-router.rule=Host(`jellyfin.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.jellyfin-router.entrypoints=http, https"
      - "traefik.http.routers.jellyfin-router.service=jellyfin-service"
      
  bitwarden:
    container_name: bitwarden
    hostname: bitwarden
    image: bitwardenrs/server
    restart: unless-stopped
    volumes:
      - /srv/data/bitwarden:/data
    environment:
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
    labels:
      - "traefik.enable=true"
      # Services
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
      # UI router
      - "traefik.http.routers.bitwarden-ui-router.rule=Host(`bitwarden.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.bitwarden-ui-router.entrypoints=http, https"
      - "traefik.http.routers.bitwarden-ui-router.service=bitwarden-ui"
      # Websocket router
      - "traefik.http.routers.bitwarden-websocket-router.rule=Host(`bitwarden.${PUBLIC_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-router.entrypoints=http, https"
      - "traefik.http.routers.bitwarden-websocket-router.service=bitwarden-websocket"
