tls:
  options:
    # https://ssl-config.mozilla.org/
    # General-purpose servers with a variety of clients, recommended for almost all systems
    # Supports Firefox 27, Android 4.4.2, Chrome 31, Edge, IE 11 on Windows 7, Java 8u31, OpenSSL 1.0.1, Opera 20, and Safari 9 
    intermediate:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    # Services with clients that support TLS 1.3 and don't need backward compatibility
    # Supports Firefox 63, Android 10.0, Chrome 70, Edge 75, Java 11, OpenSSL 1.1.1, Opera 57, and Safari 12.1 
    modern:
      minVersion: "VersionTLS13"

http:
  middlewares:

    auth:
      basicAuth:
        usersFile: /etc/traefik/auth.passwd

    https-redirect:
      redirectScheme:
        scheme: https

    security-headers:
      headers:
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
