log:
  level: INFO

accessLog:
  filePath: /dev/stdout
  bufferingSize: 1000

api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: public

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  internal:
    address: ":8443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your@email.com
      storage: /var/traefik/acme.json
      httpChallenge:
        entryPoint: http

